BLACK		equ		$0000
BLUE		equ		$001F
RED			equ		$F800
GREEN		equ		$07E0
CYAN		equ		$07FF
MAGENTA		equ		$F81F
YELLOW		equ		$FFE0
WHITE		equ		$FFFF
GRAY		equ		$8410
NAVY		equ		$000F      ;/*   0,   0, 128 */
DARKGREEN	equ		$03E0      ;/*   0, 128,   0 */
DARKCYAN	equ		$03EF      ;/*   0, 128, 128 */
MAROON		equ		$7800      ;/* 128,   0,   0 */
PURPLE		equ		$780F      ;/* 128,   0, 128 */
OLIVE		equ		$7BE0      ;/* 128, 128,   0 */
LIGHTGREY	equ		$C618      ;/* 192, 192, 192 */
DARKGREY	equ		$7BEF      ;/* 128, 128, 128 */
ORANGE		equ		$FDA0      ;/* 255, 180,   0 */
GREENYELLOW	equ		$B7E0      ;/* 180, 255,   0 */
PINK		equ		$FC9F
